### ISSUE TITLE
evaluation result

### ISSUE THREAD

**Issue by crowdcwj-ydw** [ws-choi/Conditioned-Source-Separation-LaSAFT#15]
Hi, I have already trained using the data set samples you provided, but I can't find where to get the evaluation results. Thank you very much for your help.

**Comment by ws-choi** [comment]
Hi @crowdcwj-ydw ,

Checkpoints will be stored in the following path:  ```{%workspace}/etc/checkpoints/{%model_name}/{%run_id}/*.ckpt}```

If you trained a model with the script below,

```bash shell
main.py --problem_name conditioned_separation --mode train --musdb_root ../repos/musdb18_wav --n_blocks 9 --num_tdfs 6 --n_fft 4096 --hop_length 1024 --precision 16 --embedding_dim 64 --pin_memory True --save_top_k 3 --patience 10 --deterministic --model lasaft_net --gpus 4 --distributed_backend ddp --sync_batchnorm True --run_id lasaft_2020_als --batch_size 4 --seed 2020 --log wandb --lr 0.0001 --auto_lr_schedule True
```

then it stores checkpoints in the following path: ```{%workspace}/etc/checkpoints/lasaft_net/lasaft_2020_als /*.ckpt}```.

To evaluate the performance of the trained model with the trained checkpoint,
you can use the evaluation script as follows:

```bash shell
main.py --problem_name conditioned_separation --mode eval --run_id lasaft_net --musdb_root ../data/musdb18_wav --n_blocks 9 --num_tdfs 6 --n_fft 4096 --hop_length 1024 --embedding_dim 64 --pin_memory True --num_workers 0 --model lasaft_net --gpus 1 --run_id lasaft_2020_als --batch_size 8 --epoch epoch=405.ckpt --log wandb
```

p.s. See also the [wandb report](https://wandb.ai/wschoi/lasaft/reports/LaSAFT-larger-model-training-eval-example--Vmlldzo1NDczMTM) created by the eval script above.

**Comment by crowdcwj-ydw** [comment]
Thanks. I get it.
