### ISSUE TITLE
How to train the code on local?

### ISSUE THREAD

**Issue by Logicino** [ws-choi/Conditioned-Source-Separation-LaSAFT#33]
Hello, I'm using Ubuntu 20.04 system and want to train this project on my pc.
I have downloaded the MUSDB18-HQ with all the .wav form profiles to my pc and created a conda environment with python=3.8 and torch=1.8.1 as shown in the readme.
In which path should I put my dataset? 
In data/musdb_wrapper.py I see 
`    @staticmethod
    def add_data_provider_args(parent_parser):
        parser = ArgumentParser(parents=[parent_parser], add_help=False)

        parser.add_argument('--musdb_root', type=str, default='etc/musdb18_samples_wav/')

        return parser`

does this mean I need to change the "musdb18hq" foler name(with subfolders "train" and "test") into "musdb18_samples_wav" and put into the folder "etc"? Or should I take all the song folders into the "musdb18_samples_wav" folder without subfolders "train" and "test"?
Thank you.

**Comment by ws-choi** [comment]
Hi @Logicino, Thank you for your question.

We no longer use `parser.add_argument('--musdb_root', type=str, default='etc/musdb18_samples_wav/')` cause now we are mangaging the whole project with `hydra` (https://github.com/ashleve/lightning-hydra-template).

---

Could you try this commend?

`python train.py trainer.gpus=1 dataset.batch_size=6 dataset.musdb_root=$YOURMUSDBROOT`
, where `$YOURMUSDBROOT` is your MUSDB18 directory?

**Comment by ws-choi** [comment]
Ah, you don't have to put the other options like `trainer.gpus=1 dataset.batch_size=6` if you don't need them.

**Comment by ws-choi** [comment]
Also, you might as well check our new repository of the LASAFT-Net-v2 (https://ws-choi.github.io/LASAFT-Net-v2/) if you want to try the newest model.

But sorry in advance, that repository is not well documented yet. I will revise them sooner or later.

**Comment by Logicino** [comment]
Thank you for you reply! I 

> Hi @Logicino, Thank you for your question.
> 
> We no longer use `parser.add_argument('--musdb_root', type=str, default='etc/musdb18_samples_wav/')` cause now we are mangaging the whole project with `hydra` (https://github.com/ashleve/lightning-hydra-template).
> 
> Could you try this commend?
> 
> `python train.py trainer.gpus=1 dataset.batch_size=6 dataset.musdb_root=$YOURMUSDBROOT` , where `$YOURMUSDBROOT` is your MUSDB18 directory?

1. I think this project does not use the argparser "--musdb='directory'" as we usually use the `python train.py --directory"musdb"`, so I can just take the HYDRA training method, am I correct?

2. I set the dir of LaSAFT project(at /home/usrname/Conditioned_Source_Separation_LaSAFT), and my musdb_root is in other dirpath(/dev/musdb/musdb18hq/train and /test)
As I tried this 
`python train.py trainer.gpus=1 dataset.batch_size=6 dataset.musdb_root=$YOURMUSDBROOT` in the terminal command line, it asked me to register a wandb profile(I didn't use the HYDRA and I think this is a option tool that provides some training tricks). I registered and got a API key for the wandb, and I put the API key into the terminal when asked for. 
However, then I run python it reports an error like below:
```
Global seed set to 2020
wandb: Currently logged in as: kinologic. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.13.5
wandb: Run data is saved locally in ./wandb/run-20221110_150236-293r0nox
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run grateful-bee-6
wandb: ⭐️ View project at https://wandb.ai/kinologic/lasaft
wandb: 🚀 View run at https://wandb.ai/kinologic/lasaft/runs/293r0nox
Error executing job with overrides: ['dataset.musdb_root=dev/musdb/musdb18hq/']
Traceback (most recent call last):
  File "train.py", line 24, in hydra_entry
    main(cfg)
  File "train.py", line 19, in main
    trainer.train(cfg)
  File "/home/usrname/Conditioned-Source-Separation-LaSAFT/lasaft/source_separation/conditioned/scripts/trainer.py", line 45, in train
    wandb_login(key=cfg['wandb_api_key'])
omegaconf.errors.InterpolationResolutionError: KeyError raised while resolving interpolation: "Environment variable 'wandb_api_key' not found"
    full_key: wandb_api_key
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: Synced grateful-bee-6: https://wandb.ai/kinologic/lasaft/runs/293r0nox
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221110_150236-293r0nox/logs
```

it seems the 'wandb_api_key' not found, but I really inputed the API key. Should I ask the wandb for help? Or is there any other training method without using this HYDRA?

3. I'll later try about the version 2. Thank you for your answers :)

**Comment by ws-choi** [comment]
>  I can just take the HYDRA training method, am I correct?

Yes, as you already tried.

> However, then I run python it reports an error like below:

Ah, sorry for the poor documentation. You must use `.env` file to register your wandb api key.

I revised the readme file for it.

https://github.com/ws-choi/Conditioned-Source-Separation-LaSAFT#4-logging-mandatory-wandb

Hope it works this time :)

**Comment by Logicino** [comment]
> Ah, sorry for the poor documentation. You must use `.env` file to register your wandb api key.

Thank you for your reply!
I'm sorry for these days my server's broken and I had to fix these problems which really takes time...

for the `.env` file, I pasted the wandb key into the `.env.sample` and changed its file name into `.env`, this truly solves the previous problem, thank you!
However,  this time it run into questions about 'the PyTorch_lightening trainer got an unexpected keyword argument "truncated_bptt_steps", the whole log is shown in below:
```
wandb: Currently logged in as: kinologic. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.13.5
wandb: Run data is saved locally in ./wandb/run-20221117_142143-2scwpkn6
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run sage-brook-13
wandb: ⭐️ View project at https://wandb.ai/kinologic/lasaft
wandb: 🚀 View run at https://wandb.ai/kinologic/lasaft/runs/2scwpkn6
wandb: WARNING Calling wandb.login() after wandb.init() has no effect.
wandb: logging graph, to disable use `wandb.watch(log_graph=False)`
Error executing job with overrides: ['trainer.gpus=1', 'dataset.batch_size=6', 'dataset.musdb_root=/home/data/musdb/']
Traceback (most recent call last):
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return target(*args, **kwargs)
  File "/home/usrname/anaconda3/envs/lasaft/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 339, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'truncated_bptt_steps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 28, in <module>
    hydra_entry()
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 24, in hydra_entry
    main(cfg)
  File "train.py", line 19, in main
    trainer.train(cfg)
  File "/home/usrname/Conditioned-Source-Separation-LaSAFT/lasaft/source_separation/conditioned/scripts/trainer.py", line 49, in train
    trainer = HI.trainer(cfg, callbacks=callbacks, logger=logger, _convert_="partial")
  File "/home/usrname/Conditioned-Source-Separation-LaSAFT/lasaft/utils/instantiator.py", line 44, in trainer
    return cls.instantiate(cfg['trainer'], **kwargs)
  File "/home/usrname/Conditioned-Source-Separation-LaSAFT/lasaft/utils/instantiator.py", line 52, in instantiate
    return hydra.utils.instantiate(*args, **kwargs)
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(target, *args, **kwargs)
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "/home/usrname/.local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return target(*args, **kwargs)
  File "/home/usrname/anaconda3/envs/lasaft/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 339, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: Error instantiating 'pytorch_lightning.trainer.trainer.Trainer' : __init__() got an unexpected keyword argument 'truncated_bptt_steps'
```

I think I need to look into the PyTorch lightening and the 'truncated_bptt_steps'... Do you have any idea on this problem? Thank you!

**Comment by Logicino** [comment]
> 

I think I solved this problem because of the version of pytorch lightning.
The file suggest for pytorch lightning >=1.3.2, however before I tried 1.4.0, 1.5.0, 1.5.10, 1.6.0, these won't work!
Please try to fix this suggestion :)

**Comment by Logicino** [comment]
> > I can just take the HYDRA training method, am I correct?
> 
> Yes, as you already tried.
> 
> > However, then I run python it reports an error like below:
> 
> Ah, sorry for the poor documentation. You must use `.env` file to register your wandb api key.
> 
> I revised the readme file for it.
> 
> https://github.com/ws-choi/Conditioned-Source-Separation-LaSAFT#4-logging-mandatory-wandb
> 
> Hope it works this time :)

Well, as I tried LASAFTv2(https://github.com/ws-choi/LASAFT-Net-v2), it comes up with other questions.
I have created the .env file like:
```
wandb_api_key="43a557ffd01194ec0417f41b6efb218c078275f1" # go wandb.ai/settings and copy your key
data_dir="/home/data/musdb" # Your Musdb data directory. must be an absolute path.
HYDRA_FULL_ERROR=1 
```
and as I tried to train LASAFTv2 using:
```
(lasaft) usrname@ubuntu-18:~/LASAFT-Net-v2$ python train.py trainer.gpus=1 dataset.batch_size=6 --version=v2
usage: train.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--resolve] [--package PACKAGE]
                [--run] [--multirun] [--shell-completion] [--config-path CONFIG_PATH] [--config-name CONFIG_NAME]
                [--config-dir CONFIG_DIR] [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
                [overrides [overrides ...]]
train.py: error: argument --version: ignored explicit argument 'v2'
```
It seems it is not the proper command to train this. As I looked into the project of LASAFTv2, I didn't see any suggestions about training. Could you please tell me? Thank you!

**Comment by Logicino** [comment]
I have fixed all the problems of this project 👍 Thank you~
I'm looking forward to the document update of LASAFTv2 :)

**Comment by Logicino** [comment]
> I think I solved this problem because of the version of pytorch lightning.
> The file suggest for pytorch lightning >=1.3.2, however before I tried 1.4.0, 1.5.0, 1.5.10, 1.6.0, these won't work!
> Please try to fix this suggestion :)

this can only be 1.3.2

**Comment by ws-choi** [comment]
Hi @Logicino , thanks a lot for letting me know that issue.

I'll update this and v2 repository sooner or later (or you can make a PR if you want :) )
