### ISSUE TITLE
how to run in distributed mode

### ISSUE THREAD

**Issue by sun-peach** [ws-choi/Conditioned-Source-Separation-LaSAFT#7]
Hi, I have not use pytorch_lightning before. I am dealing with large amount of data now. In you demo, you only show how to run with 1 GPU. Now I would like to run in multiple GPU modes. How can I do it?

I have simply set gpus to 4, but it showed errors.

Thank you very much!

**Comment by ws-choi** [comment]
Hi @sun-peach ,
>I have simply set gpus to 4, but it showed errors.

Can you share the code or script that you've run?

**Comment by sun-peach** [comment]
I still use your code, but during running, I am using --gpus 4 option.

**Comment by ws-choi** [comment]
I thought you've tried to use the evaluation mode with muti-gpus, 
but it seems like you want to train our model with your own dataset!
I am sorry that I misunderstood.

Have you tried the distributed backend option with ddp?
Below is the script I've used.

```
python main.py --problem_name conditioned_separation --mode train --musdb_root ../repos/musdb18_wav --n_blocks 9 --num_tdfs 6 --n_fft 4096 --hop_length 1024 --precision 16 --embedding_dim 64 --pin_memory True --save_top_k 3 --patience 10 --deterministic --model lasaft_net --gpus 4 --distributed_backend ddp --sync_batchnorm True --run_id lasaft_2020_als --batch_size 4 --seed 2020 --log wandb --lr 0.0001 --auto_lr_schedule True
```
